# app/models/labor_item.py
from decimal import Decimal
from sqlalchemy import (
    Column,
    String,
    Numeric,
)
from app.db.base import Base
from app.models.mixins.base_cost_item import BaseCostItemMixin
from sqlalchemy.orm import Mapped, mapped_column
from datetime import datetime

class LaborItem(Base, BaseCostItemMixin):
    """
    Labor cost item.
    Represents labor cost generated by a production / construction group.
    """

    __tablename__ = "labor_items"

    # =========
    # 👥 Group naming
    # =========
    raw_group :Mapped[str] = mapped_column(
        String(255),
        nullable=True,
        comment="Raw group name from Excel, immutable",
    )

    normalized_group :Mapped[str] = mapped_column(
        String(255),
        nullable=True,
        comment="Normalized group name, editable with AuditLog",
    )

    # =========
    # 🔢 Workload & pricing
    # =========
    work_quantity :Mapped[Decimal] = mapped_column(
        Numeric(12, 5),
        nullable=True,
        comment="Workload quantity (e.g. ton, kg, meter, unit)",
    )

    unit :Mapped[str] = mapped_column(
        String(50),
        nullable=True,
        comment="Unit of workload",
    )

    unit_price :Mapped[Decimal] = mapped_column(
        Numeric(12, 5),
        nullable=True,
        comment="Labor cost per unit",
    )
    extra_subsidies :Mapped[Decimal] = mapped_column(
        Numeric(14, 5),
        nullable=True,
        comment="Extra subsidies for the labor group",
    )
    ton_bonus :Mapped[Decimal] = mapped_column(
        Numeric(14, 5),
        nullable=True,
        comment="Ton-based bonus for the labor group",
    )
    subtotal :Mapped[Decimal] = mapped_column(
        Numeric(14, 5),
        nullable=True,
        comment="System-calculated labor cost subtotal",
    )

    # =========
    # Optional: representation
    # =========
    def __repr__(self) -> str:
        return (
            f"<LaborItem id={self.id} "
            f"group={self.normalized_group or self.raw_group} "
            f"subtotal={self.subtotal}>"
        )
