#app/agentic/fsm/enums.py
#FSM状态枚举

from enum import Enum

class CostCalcState(str, Enum):
    S0_INIT = "S0_INIT"
    S1_INPUT_GATE = "S1_INPUT_GATE"
    S2_CREATE_PROJECT = "S2_CREATE_PROJECT"
    S3_PARSE_FILES = "S3_PARSE_FILES"
    S4_VALIDATION_CORRECTION_LOOP = "S4_VALIDATION_CORRECTION_LOOP"
    S5_GENERATE_COST_SUMMARY = "S5_GENERATE_COST_SUMMARY"
    S6_GENERATE_COST_REPORT = "S6_GENERATE_COST_REPORT"
    S7_PUBLISH_AND_SUMMARIZE = "S7_PUBLISH_AND_SUMMARIZE"
    S8_DONE = "S8_DONE"

    S_WAIT_USER = "S_WAIT_USER"
    S_ERR_ESCALATE = "S_ERR_ESCALATE"